"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gốc dự án (2 cấp trên BASE_DIR=source/backend/). Dữ liệu dùng chung giữa
# crawler và backend nằm ở đây, không nằm trong project Django.
PROJECT_ROOT = BASE_DIR.parent.parent
DATA_DIR = PROJECT_ROOT / "data"


def _doc_env(duong_dan):
    """Nạp .env dạng KEY=VALUE vào os.environ — không cần python-dotenv.

    .env nằm trong .gitignore nên khoá bí mật không lọt vào git.
    Biến môi trường thật (nếu có) luôn thắng file: setdefault, không ghi đè.
    """
    if not duong_dan.exists():
        return
    for dong in duong_dan.read_text(encoding="utf-8").splitlines():
        dong = dong.strip()
        if not dong or dong.startswith("#") or "=" not in dong:
            continue
        ten, _, gia_tri = dong.partition("=")
        os.environ.setdefault(ten.strip(), gia_tri.strip().strip("'\""))


_doc_env(PROJECT_ROOT / ".env")
_doc_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-8@srnic7)2+dsnl!0oy9e#b4l31-p0e@c)57b3+u$-_&-st_e(')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS =  [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1'
    ).split(',')
    if host.strip()
]

# OAuth (accounts/views_oauth.py). Nút nào chưa cấu hình báo lỗi chứ không sập trang.
# Google: Google Cloud Console -> Credentials -> OAuth client ID.
#   Redirect URI: "<host>/accounts/google/xac-thuc/"
# Facebook: Facebook for Developers -> OAuth client. Valid OAuth Redirect URIs:
#   "<host>/accounts/facebook/xac-thuc/" (facebook bắt buộc https, trừ localhost)
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'university',
    'accounts',
    'admissions',
    'recommendation',
    'quantri',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates" # cấu hình trang header và footer
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'university.context_processors.cua_so_nam',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'uni_map'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Locale vi dùng "." làm dấu phân cách nghìn — khớp mockup UI_unimap (178.825).
USE_THOUSAND_SEPARATOR = True
# Django 5.x locale vi có THOUSAND_SEPARATOR='.' nhưng NUMBER_GROUPING=0
# (grouping tắt) nên intcomma trả về không dấu. ép group theo nhóm 3 chữ số.
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Toàn bộ UI dùng Tailwind + Material Symbols qua CDN; logo là SVG inline ở
# templates/partials/logo.html, nên không còn file static tự quản.
STATIC_URL = 'static/'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# `Nganh.nganh_slug` là UNIQUE dài 320 ký tự. Django cảnh báo mysql.W003 vì mặc
# định giả định index giới hạn 255 ký tự — đúng với MySQL cũ (COMPACT row
# format, khoá index 767 byte). MySQL 8 mặc định DYNAMIC: index tới 3072 byte
# = 768 ký tự utf8mb4, nên 320 an toàn. Đã kiểm chứng bằng `SHOW CREATE TABLE`.
SILENCED_SYSTEM_CHECKS = ["mysql.W003"]

LOGIN_URL = "accounts:dang_nhap"
LOGIN_REDIRECT_URL = "university:trang_chu"
LOGOUT_REDIRECT_URL = "university:trang_chu"


