# Generated by Django 5.2.8 on 2026-09-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaSoNam',
            fields=[
                ('vi_tri', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nam', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'cua_so_nam',
                'ordering': ['vi_tri'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DacTrungDiemChuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(choices=[('Điểm thi THPT', 'Điểm thi THPT'), ('Điểm học bạ', 'Điểm học bạ')], max_length=13)),
                ('diem_nam_1', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('diem_nam_2', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('diem_nam_3', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('diem_nam_4', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('diem_nam_5', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('diem_tb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diem_moi_nhat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bien_dong', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xu_huong', models.DecimalField(decimal_places=3, max_digits=6)),
                ('so_nam_co_dl', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'dac_trung_diemchuan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiemChuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(choices=[('Điểm thi THPT', 'Điểm thi THPT'), ('Điểm học bạ', 'Điểm học bạ')], max_length=13)),
                ('nam', models.PositiveSmallIntegerField()),
                ('diem_chuan', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ten_nganh_goc', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'diem_chuan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiemMon',
            fields=[
                ('pk', models.CompositePrimaryKey('ho_so_id', 'ma_mon', blank=True, editable=False, primary_key=True, serialize=False)),
                ('diem', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'diem_mon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoSoNangLuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ho_so', models.CharField(default='Hồ sơ của tôi', max_length=100)),
                ('phuong_thuc', models.CharField(choices=[('Điểm thi THPT', 'Điểm thi THPT'), ('Điểm học bạ', 'Điểm học bạ')], default='Điểm thi THPT', max_length=13)),
                ('diem_uu_tien', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('vung_mien_uu_tien', models.CharField(blank=True, default='', max_length=60)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_sua', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ho_so_nang_luc',
                'ordering': ['-ngay_sua'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KetQuaGoiY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(choices=[('Điểm thi THPT', 'Điểm thi THPT'), ('Điểm học bạ', 'Điểm học bạ')], max_length=13)),
                ('diem_hoc_sinh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xac_suat_do', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tang', models.CharField(choices=[('An toàn', 'An toàn'), ('Vừa sức', 'Vừa sức'), ('Thử sức', 'Thử sức')], max_length=7)),
                ('thu_hang', models.PositiveSmallIntegerField()),
                ('da_luu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ket_qua_goi_y',
                'ordering': ['thu_hang'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanCapNhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_diem', models.DateTimeField()),
                ('nguon', models.CharField(max_length=100)),
                ('nam_bat_dau', models.PositiveSmallIntegerField()),
                ('nam_ket_thuc', models.PositiveSmallIntegerField()),
                ('so_truong', models.PositiveSmallIntegerField()),
                ('so_nganh', models.PositiveSmallIntegerField()),
                ('so_dong_diem', models.PositiveIntegerField()),
                ('selfcheck_dat', models.BooleanField()),
                ('ghi_chu', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'lan_cap_nhat',
                'ordering': ['-thoi_diem'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanGoiY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_diem', models.DateTimeField(auto_now_add=True)),
                ('phien_ban_mo_hinh', models.CharField(blank=True, default='', max_length=50)),
                ('dung_ai', models.BooleanField(default=True)),
                ('so_ket_qua', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'lan_goi_y',
                'ordering': ['-thoi_diem'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mon',
            fields=[
                ('ma_mon', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ten_mon', models.CharField(max_length=60)),
                ('la_nang_khieu', models.BooleanField()),
                ('thu_tu', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mon',
                'ordering': ['thu_tu'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('nganh_id', models.AutoField(primary_key=True, serialize=False)),
                ('nganh_slug', models.CharField(max_length=120, unique=True)),
                ('ten_nganh', models.CharField(max_length=320)),
                ('nhom_nganh', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'nganh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhomNganhQuanTam',
            fields=[
                ('pk', models.CompositePrimaryKey('ho_so_id', 'nhom_nganh', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nhom_nganh', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'nhom_nganh_quan_tam',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToHop',
            fields=[
                ('ma_to_hop', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ten_to_hop', models.CharField(max_length=80)),
                ('cac_mon', models.CharField(help_text='TOAN,LI,HOA', max_length=60)),
                ('so_mon', models.PositiveIntegerField()),
                ('nguon', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'to_hop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToHopMon',
            fields=[
                ('pk', models.CompositePrimaryKey('ma_to_hop', 'ma_mon', 'vi_tri', blank=True, editable=False, primary_key=True, serialize=False)),
                ('vi_tri', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'to_hop_mon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('ma_truong', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_truong', models.CharField(max_length=150)),
                ('viet_tat', models.CharField(max_length=20)),
                ('tinh_thanh', models.CharField(max_length=30)),
                ('vung_mien', models.CharField(choices=[('Miền Bắc', 'Miền Bắc'), ('Miền Trung', 'Miền Trung'), ('Miền Nam', 'Miền Nam')], max_length=10)),
            ],
            options={
                'db_table': 'truong',
                'managed': False,
            },
        ),
    ]
